// import { TVResponse } from "@/types";
"use client";
import React from "react";
import TvListing from "./TvListing";
import { useGetTrendingTVQuery } from "@/lib/features/trendings/trendingApiSlice";
import TrendingSkeleton from "./TrendingSkeleton";

const TrendingTv = () => {
  // const dummy: TVResponse = {
  //   page: 1,
  //   results: [
  //     {
  //       backdrop_path: "/sYXLeu5usz6yEz0k00FYvtEdodD.jpg",
  //       id: 94605,
  //       name: "Arcane",
  //       original_name: "Arcane",
  //       overview:
  //         "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
  //       poster_path: "/abf8tHznhSvl9BAElD2cQeRr7do.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [16, 10765, 10759, 9648],
  //       popularity: 1130.512,
  //       first_air_date: "2021-11-06",
  //       vote_average: 8.767,
  //       vote_count: 4469,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/pP9Or3dN8k0go1G2OSldcwBpUFO.jpg",
  //       id: 211039,
  //       name: "Senna",
  //       original_name: "Senna",
  //       overview:
  //         "Fascinated by cars since childhood, Brazilian racer Ayrton Senna became a sports legend — until tragedy struck, changing Formula 1 forever.",
  //       poster_path: "/yxkrrtyOzx36uHowqYB3Ec8b9wg.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "pt",
  //       genre_ids: [18],
  //       popularity: 206.226,
  //       first_air_date: "2024-11-29",
  //       vote_average: 7.6,
  //       vote_count: 15,
  //       origin_country: ["BR"],
  //     },
  //     {
  //       backdrop_path: "/4xlGZgROYLB8nJsmOadtHhl418u.jpg",
  //       id: 250308,
  //       name: "Earth Abides",
  //       original_name: "Earth Abides",
  //       overview:
  //         "When a plague of unprecedented virulence sweeps the globe, the human race is all but wiped out. In the aftermath, as the great machine of civilization slowly and inexorably breaks down, only a few shattered survivors remain to struggle against the slide into extinction.",
  //       poster_path: "/s0RSMjbOm7TVvFoAavotSvuQ5xL.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [10765],
  //       popularity: 119.031,
  //       first_air_date: "2024-12-01",
  //       vote_average: 7.3,
  //       vote_count: 7,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/o9gr7EoGPDU1IIv8Buzm2neklUM.jpg",
  //       id: 219971,
  //       name: "The Agency",
  //       original_name: "The Agency",
  //       overview:
  //         "Covert CIA agent Martian is ordered to abandon his undercover life and return to London Station. When the love he left behind unexpectedly reappears, their romance reignites, pitting his career, his real identity and his mission against his heart while hurling them both into a deadly game of international intrigue and espionage.",
  //       poster_path: "/j0fFZIksd4nu8bNLGLq8GJ4KXFA.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [18, 9648],
  //       popularity: 162.817,
  //       first_air_date: "2024-12-01",
  //       vote_average: 8.1,
  //       vote_count: 12,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/enVrO8TRkdT8dmYXTfI4sEjR5Kp.jpg",
  //       id: 222766,
  //       name: "The Day of the Jackal",
  //       original_name: "The Day of the Jackal",
  //       overview:
  //         "An unrivalled and highly elusive lone assassin, the Jackal, makes his living carrying out hits for the highest fee. But following his latest kill, he meets his match in a tenacious British intelligence officer who starts to track down the Jackal in a thrilling cat-and-mouse chase across Europe, leaving destruction in its wake.",
  //       poster_path: "/4hSnGq014MGdxCOMWBwyvKoDjrF.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [18, 10759, 9648],
  //       popularity: 805.458,
  //       first_air_date: "2024-11-07",
  //       vote_average: 8.077,
  //       vote_count: 91,
  //       origin_country: ["GB"],
  //     },
  //     {
  //       backdrop_path: "/79DCyZhUcFsiGfyjNlFH1lS1t4c.jpg",
  //       id: 230777,
  //       name: "The Trunk",
  //       original_name: "트렁크",
  //       overview:
  //         "A secret marriage service is uncovered when a trunk washes up on the shore, revealing the strange marriage between a couple in the thick of it all.",
  //       poster_path: "/6gQ1JEIgQCOcy01GESYszrH3FfA.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "ko",
  //       genre_ids: [18, 9648],
  //       popularity: 179.309,
  //       first_air_date: "2024-11-29",
  //       vote_average: 8,
  //       vote_count: 5,
  //       origin_country: ["KR"],
  //     },
  //     {
  //       backdrop_path: "/wf40RT8DTJfdwOLIbVD18XLcnKY.jpg",
  //       id: 277414,
  //       name: "Banned Tape",
  //       original_name: "Rekaman Terlarang",
  //       overview:
  //         "Rena, the daughter of a conservative governor, is pressured to marry Dandy, the son of her father's powerful political ally. Although she still has deep feelings for her ex, Bayu, who happens to be the organizer of their wedding.",
  //       poster_path: "/41MrZENGRsQXJdnnxg0KeiKcW0N.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "id",
  //       genre_ids: [18],
  //       popularity: 4.074,
  //       first_air_date: "2024-10-24",
  //       vote_average: 0,
  //       vote_count: 0,
  //       origin_country: ["ID"],
  //     },
  //     {
  //       backdrop_path: "/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg",
  //       id: 125988,
  //       name: "Silo",
  //       original_name: "Silo",
  //       overview:
  //         "In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts to uncover shocking secrets and the truth about the silo.",
  //       poster_path: "/tlliQuCupf8fpTH7RAor3aKMGy.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [10765, 18],
  //       popularity: 1275.834,
  //       first_air_date: "2023-05-04",
  //       vote_average: 8.156,
  //       vote_count: 1078,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/2Erj4Oav9EHAtqLI354VM7ULDqu.jpg",
  //       id: 73586,
  //       name: "Yellowstone",
  //       original_name: "Yellowstone",
  //       overview:
  //         "Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States. Led by their patriarch John Dutton, the family defends their property against constant attack by land developers, an Indian reservation, and America’s first National Park.",
  //       poster_path: "/s4QRRYc1V2e68Qy9Wel9MI8fhRP.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [37, 18],
  //       popularity: 1430.907,
  //       first_air_date: "2018-06-20",
  //       vote_average: 8.2,
  //       vote_count: 2400,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/r0Zg70jpcDAD7IMDhVqajSnG9vb.jpg",
  //       id: 113962,
  //       name: "Lioness",
  //       original_name: "Lioness",
  //       overview:
  //         "Cruz Manuelos, a rough-around-the-edges but passionate young Marine, is recruited to join the CIA's Lioness Engagement Team to help bring down a terrorist organization from within. Joe, the station chief of the Lioness program, is tasked with training, managing and leading her female undercover operatives.",
  //       poster_path: "/ajaXSmdAlYYhnvx1EIsvpfN949y.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [18, 10768],
  //       popularity: 953.542,
  //       first_air_date: "2023-07-23",
  //       vote_average: 8.02,
  //       vote_count: 748,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/2IcQsas0BGYQMkF6yixUCY2k2qp.jpg",
  //       id: 73982,
  //       name: "Day and Night",
  //       original_name: "白夜追凶",
  //       overview:
  //         "Twin brothers Guan Hongfeng and Guan Hongyu find themselves caught up in a brutal massacre that destroyed their family. As they face off against a shadowy criminal organization, they join forces with others to uncover the truth behind the 213 massacre.",
  //       poster_path: "/uuKmigg4WuduZMJKIzJ8UP02pRg.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "zh",
  //       genre_ids: [80, 18, 9648],
  //       popularity: 569.066,
  //       first_air_date: "2017-08-30",
  //       vote_average: 8.3,
  //       vote_count: 39,
  //       origin_country: ["CN"],
  //     },
  //     {
  //       backdrop_path: "/5J9cs2mtbL0ic4qmf3r3TuUttOD.jpg",
  //       id: 220056,
  //       name: "The Madness",
  //       original_name: "The Madness",
  //       overview:
  //         "After a media pundit stumbles upon a dead body deep in the Poconos woods, he finds himself framed for the murder of a notorious white supremacist.",
  //       poster_path: "/z3KaWe2r0yBaRbQlH7BPOR5fpnL.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [18, 80, 10759],
  //       popularity: 243.848,
  //       first_air_date: "2024-11-28",
  //       vote_average: 7.3,
  //       vote_count: 16,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/o0NsbcIvsllg6CJX0FBFY8wWbsn.jpg",
  //       id: 30984,
  //       name: "Bleach",
  //       original_name: "BLEACH",
  //       overview:
  //         "For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever. Now, with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil.",
  //       poster_path: "/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "ja",
  //       genre_ids: [10759, 16, 10765],
  //       popularity: 373.595,
  //       first_air_date: "2004-10-05",
  //       vote_average: 8.4,
  //       vote_count: 1843,
  //       origin_country: ["JP"],
  //     },
  //     {
  //       backdrop_path: "/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
  //       id: 37854,
  //       name: "One Piece",
  //       original_name: "ワンピース",
  //       overview:
  //         'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
  //       poster_path: "/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "ja",
  //       genre_ids: [10759, 35, 16],
  //       popularity: 110.985,
  //       first_air_date: "1999-10-20",
  //       vote_average: 8.7,
  //       vote_count: 4720,
  //       origin_country: ["JP"],
  //     },
  //     {
  //       backdrop_path: "/q3UGWifvIpdey1T2efX4dSmbZpU.jpg",
  //       id: 124364,
  //       name: "FROM",
  //       original_name: "FROM",
  //       overview:
  //         "Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.",
  //       poster_path: "/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [9648, 18, 10765],
  //       popularity: 1514.868,
  //       first_air_date: "2022-02-20",
  //       vote_average: 8.2,
  //       vote_count: 1530,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/mh2UczqEXJJVgqohbyZbHTuxwhL.jpg",
  //       id: 157741,
  //       name: "Landman",
  //       original_name: "Landman",
  //       overview:
  //         "Set in the proverbial boomtowns of West-Texas and a modern-day tale of fortune-seeking in the world of oil rigs, the series is an upstairs/downstairs story of roughnecks and wildcat billionaires that are fueling a boom so big it’s reshaping our climate, our economy and our geopolitics.",
  //       poster_path: "/rxWtATtTdwx0ERQjQ7BtVOMyq5r.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [18],
  //       popularity: 410.851,
  //       first_air_date: "2024-11-17",
  //       vote_average: 7.8,
  //       vote_count: 31,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/jeqqR0FuJeXgc7e6rzBVSSWPP7o.jpg",
  //       id: 226649,
  //       name: "The Tale of Lady Ok",
  //       original_name: "옥씨부인전",
  //       overview:
  //         "A drama that depicts the fierce survival and success of a female slave in the Joseon Dynasty, and the story of a woman whose name, identity, and even her husband were all fake.",
  //       poster_path: "/3cfo9NH2wZ0fm8TbiN7L8NREM0Q.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "ko",
  //       genre_ids: [18],
  //       popularity: 71.07,
  //       first_air_date: "2024-11-30",
  //       vote_average: 5,
  //       vote_count: 1,
  //       origin_country: ["KR"],
  //     },
  //     {
  //       backdrop_path: "/nf3Vlxm3C9U1aKUUQHmKFZmxPSc.jpg",
  //       id: 56570,
  //       name: "Outlander",
  //       original_name: "Outlander",
  //       overview:
  //         "The story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened. When she is forced to marry Jamie, a chivalrous and romantic young Scottish warrior, a passionate affair is ignited that tears Claire's heart between two vastly different men in two irreconcilable lives.",
  //       poster_path: "/oftZNfyTVNU7IfOqoGLoT8MGvNs.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [18, 10765],
  //       popularity: 302.639,
  //       first_air_date: "2014-08-09",
  //       vote_average: 8.2,
  //       vote_count: 2583,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/qq36sU5xH581RiNEkookMQ9D7yp.jpg",
  //       id: 194764,
  //       name: "The Penguin",
  //       original_name: "The Penguin",
  //       overview:
  //         'With the city in peril following the seawall\'s collapse, Oswald "Oz" Cobb seeks to fill the power vacuum left by the death of Carmine Falcone and finally give his mother Francis the life he\'s always promised. But first, Oz must confront his enemies and his own demoralizing reputation as "the Penguin."',
  //       poster_path: "/a2fqompEWB2GFp9GOdlqLcfEFfw.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [18, 80],
  //       popularity: 351.099,
  //       first_air_date: "2024-09-19",
  //       vote_average: 8.5,
  //       vote_count: 559,
  //       origin_country: ["US"],
  //     },
  //     {
  //       backdrop_path: "/C7sPx6EY23MIKzEMvk8T0qScio.jpg",
  //       id: 202879,
  //       name: "Star Wars: Skeleton Crew",
  //       original_name: "Star Wars: Skeleton Crew",
  //       overview:
  //         "Four ordinary kids search for their home planet after getting lost in the Star Wars galaxy.",
  //       poster_path: "/6WK3oVHXnAbQgwvUcqLYlRp8Bvq.jpg",
  //       media_type: "tv",
  //       adult: false,
  //       original_language: "en",
  //       genre_ids: [10759, 10765],
  //       popularity: 105.018,
  //       first_air_date: "2024-12-02",
  //       vote_average: 9,
  //       vote_count: 1,
  //       origin_country: ["US"],
  //     },
  //   ],
  //   total_pages: 500,
  //   total_results: 10000,
  // };
  const { data: Tv, isLoading, isError, isSuccess } = useGetTrendingTVQuery({});

  if (isLoading) {
    return <TrendingSkeleton />;
  }
  if (isError) {
    return <p>Error Loading stuff</p>;
  }
  return (
    <div>
      <h1>Trending TV</h1>

      {isSuccess && <TvListing tvListings={Tv} />}
    </div>
  );
};

export default TrendingTv;
