import React from "react";
import PeopleListing from "./PeopleListing";
import { PeopleResponse } from "@/types";

const TrendingPeople = () => {
  const dummy: PeopleResponse = {
    page: 1,
    results: [
      {
        id: 124010,
        name: "Sarah Marshall",
        original_name: "Sarah Marshall",
        media_type: "person",
        adult: false,
        popularity: 3.533,
        gender: 1,
        known_for_department: "Acting",
        profile_path: "/1HW2RF9ZywXM12I6Kfla9KoTIWd.jpg",
      },
      {
        id: 2349944,
        name: "Yoo Jung",
        original_name: "유정",
        media_type: "person",
        adult: false,
        popularity: 28.419,
        gender: 1,
        known_for_department: "Acting",
        profile_path: "/an05J38LZGz3sdDe0CxxXUIGHe9.jpg",
      },
      {
        id: 11505,
        name: "John Hughes",
        original_name: "John Hughes",
        media_type: "person",
        adult: false,
        popularity: 11.211,
        gender: 2,
        known_for_department: "Writing",
        profile_path: "/nfGhXH2zcGPAOw8kNbnes516aZG.jpg",
      },
      {
        id: 3831799,
        name: "Jeff Dobbs",
        original_name: "Jeff Dobbs",
        media_type: "person",
        adult: false,
        popularity: 0.001,
        gender: 0,
        known_for_department: "Production",
        profile_path: null,
      },
      {
        id: 51576,
        name: "Chuck Norris",
        original_name: "Chuck Norris",
        media_type: "person",
        adult: false,
        popularity: 24.058,
        gender: 2,
        known_for_department: "Acting",
        profile_path: "/m3uLikdhi9qObRvGVHsKX5H93lR.jpg",
      },
      {
        id: 3164807,
        name: "Yoon Yool",
        original_name: "Yoon Yool",
        media_type: "person",
        adult: false,
        popularity: 86.518,
        gender: 1,
        known_for_department: "Acting",
        profile_path: "/21kdujBeL2hrJ50RyMxmuEsHZAT.jpg",
      },
      {
        id: 12799,
        name: "Jeremy Piven",
        original_name: "Jeremy Piven",
        media_type: "person",
        adult: false,
        popularity: 37.3,
        gender: 2,
        known_for_department: "Acting",
        profile_path: "/pBD1jcAZiDrHWcFpJtBtqLRD4gR.jpg",
      },
      {
        id: 3493970,
        name: "张子扬",
        original_name: "张子扬",
        media_type: "person",
        adult: false,
        popularity: 0.001,
        gender: 0,
        known_for_department: "Acting",
        profile_path: null,
      },
      {
        id: 3165040,
        name: "Rika",
        original_name: "Rika",
        media_type: "person",
        adult: false,
        popularity: 67.789,
        gender: 1,
        known_for_department: "Acting",
        profile_path: "/vwYqrhcSRVrnra4S0NopnywN8rK.jpg",
      },
      {
        id: 5009979,
        name: "河北彩花",
        original_name: "河北彩花",
        media_type: "person",
        adult: false,
        popularity: 8.299,
        gender: 1,
        known_for_department: null,
        profile_path: "/pDVfME2z2DiosnHFBALHvoSvqs5.jpg",
      },
      {
        id: 1622390,
        name: "Lee Chae-dam",
        original_name: "Lee Chae-dam",
        media_type: "person",
        adult: false,
        popularity: 28.121,
        gender: 1,
        known_for_department: "Acting",
        profile_path: "/7wMyr6F3yzvbSpu2XMxSW3vObED.jpg",
      },
      {
        id: 578,
        name: "Ridley Scott",
        original_name: "Ridley Scott",
        media_type: "person",
        adult: false,
        popularity: 33.847,
        gender: 2,
        known_for_department: "Directing",
        profile_path: "/zABJmN9opmqD4orWl3KSdCaSo7Q.jpg",
      },
      {
        id: 2414292,
        name: "Kiyoshi Tateishi",
        original_name: "立石聖",
        media_type: "person",
        adult: false,
        popularity: 1.397,
        gender: 2,
        known_for_department: "Visual Effects",
        profile_path: null,
      },
      {
        id: 4857254,
        name: "Ji Eun-seo",
        original_name: "Ji Eun-seo",
        media_type: "person",
        adult: false,
        popularity: 30.329,
        gender: 1,
        known_for_department: "Acting",
        profile_path: "/cg0RniDhwpVKSZaWsi614bMsJXj.jpg",
      },
      {
        id: 4431120,
        name: "John Rey Malto",
        original_name: "John Rey Malto",
        media_type: "person",
        adult: false,
        popularity: 0.356,
        gender: 2,
        known_for_department: "Production",
        profile_path: "/nnni3qnk2EvLY9F8pmY9DQaA2Ud.jpg",
      },
      {
        id: 2213661,
        name: "Matthew Ryan Anderson",
        original_name: "Matthew Ryan Anderson",
        media_type: "person",
        adult: false,
        popularity: 0.001,
        gender: 2,
        known_for_department: "Directing",
        profile_path: null,
      },
      {
        id: 1846925,
        name: "Aleksandre Digmelovi",
        original_name: "Aleksandre Digmelovi",
        media_type: "person",
        adult: false,
        popularity: 0.001,
        gender: 0,
        known_for_department: "Crew",
        profile_path: null,
      },
      {
        id: 24528,
        name: "Matthew R. Anderson",
        original_name: "Matthew R. Anderson",
        media_type: "person",
        adult: false,
        popularity: 3.713,
        gender: 2,
        known_for_department: "Acting",
        profile_path: "/6NJI6IX1V07j9oFaVBpEpoiaa6u.jpg",
      },
      {
        id: 31,
        name: "Tom Hanks",
        original_name: "Tom Hanks",
        media_type: "person",
        adult: false,
        popularity: 80.855,
        gender: 2,
        known_for_department: "Acting",
        profile_path: "/eKF1sGJRrZJbfBG1KirPt1cfNd3.jpg",
      },
      {
        id: 5009810,
        name: "河北彩花",
        original_name: "河北彩花",
        media_type: "person",
        adult: false,
        popularity: 8.072,
        gender: 1,
        known_for_department: "Acting",
        profile_path: "/5mH6mkgwFZmeYTJpxVTaqbF3uIn.jpg",
      },
    ],
    total_pages: 139,
    total_results: 2776,
  };
  return (
    <div>
      <h1>Trending People</h1>

      <PeopleListing peoplelistings={dummy} />
    </div>
  );
};

export default TrendingPeople;
